#
# Copyright (c) 2000-2002 Silicon Graphics, Inc.  All Rights Reserved.
#

TOPDIR = ..
include $(TOPDIR)/include/builddefs

LSRCFILES = builddefs.in buildmacros buildrules config.h.in dqblk_xfs.h

default install install-dev :

include $(BUILDRULES)
